### ISSUE TITLE
did you even run the application after the changes you made ?

### ISSUE THREAD

**Issue by sajis997** [daw42/glslcookbook#27]
None of the application works properly, either getting a blank window, or the camera is inside the object. Even I had the issue with macros like #define uint unsigned int. It did not compile on my ubuntu system , had to get around with typedef unsigned int uint. 

Please test the exaples if you really want to supprt the reader who spent resources on this.

**Comment by daw42** [comment]
Please note that the code has been updated to support GLM 0.9.6.  Please try with GLM 0.9.6.  Thanks.
