### ISSUE TITLE
Error in bezcurve.tcs (OK in the book's text)

### ISSUE THREAD

**Issue by arampl** [daw42/glslcookbook#28]
Hi!
~~~~~~~
    gl_TessLevelOuter[0] = float(NumSegments);
    gl_TessLevelOuter[1] = float(NumStrips);
~~~~~~~
should be:
~~~~~~~
    gl_TessLevelOuter[0] = float(NumStrips);
    gl_TessLevelOuter[1] = float(NumSegments);
~~~~~~~
Best regards!

**Comment by daw42** [comment]
Hi arampl,

Thanks for the report.  Unfortunately, I've found that this works with some drivers and not with others.  I added a comment to the code to indicate this:

https://github.com/daw42/glslcookbook/blob/master/chapter06/shader/bezcurve.tcs#L13-14

The code works properly on Intel cards (recently tested).  What driver are you using?  The GL Spec indicates that outer level 0 should be the number of strips and outer level 1 should be the number of segments (see page 393 in the GL 4.5 spec.).  Unfortunately, it looks like some drivers have it switched.

Should we add a more descriptive comment to the code?

**Comment by arampl** [comment]
I am using Xubuntu 13.10 (64 bit), videocard Nvidia GeForce GTX 560 Ti,  driver v. 319.32
For OpenGL I use GLFW 3.1, context: version 4.1 (also shader version 4.1) core profile & forward compat.

More descriptive comments would be welcome, yes. Thank You!
Very sad that this is issue with drivers...

**Comment by daw42** [comment]
I went with the book's code because it follows the OpenGL spec, and I added a more descriptive comment.  See cf66697e40b2ff75b4941b1004e2635c30966d91.  

Thanks again for the report.
