### ISSUE TITLE
compile error in Visual Studio

### ISSUE THREAD

**Issue by xzwang2005** [daw42/glslcookbook#30]
hi,

I got this error when compiling the teapot object:
error C2719: 'lidTransform': formal parameter with __declspec(align('16')) won't be aligned

I'm using Visual Studio 2013.  It can be fixed by changing the type from 'mat4' to 'mat4&', but I'm not sure if it is the best way to do it.

**Comment by daw42** [comment]
Thanks for the report.  Seems like changing to a `const mat4 &` should be a fine solution.  I'll look into this a bit more and get back to you.

**Comment by jacobodeharo** [comment]
Hi, I got the same issue compiling the solution. But in the ingredients project. 

vboteapot.cpp(14): error C2719: 'lidTransform': formal parameter with __declspec(align('16')) won't be aligned
vboteapot.cpp(89): error C2719: 'lidTransform': formal parameter with __declspec(align('16')) won't be aligned

**Comment by daw42** [comment]
I'm not seeing this error on VisualStudio 2013.  I'm using GLM 0.9.6.3.  What version of GLM are you using?  If you're using an older version, please try with the latest and let me know.

Thanks.

**Comment by xzwang2005** [comment]
i'm using glm 0.9.6.3 as well. Here's a thread talking about the same issue:
http://stackoverflow.com/questions/28488986/c-opengl-formal-parameter-with-declspecalign16-wont-be-aligned

**Comment by daw42** [comment]
Looks like the issue only occurs when building for 32-bit (win32/x86).  It doesn't happen when building for x64.  I'll change the parameter to `const mat4 &`

**Comment by daw42** [comment]
Similar issue generates a bunch of C4316 compiler warnings (`object allocated on the heap may not be aligned 16`) when targeting 32-bit.  There's an open issue on the GLM repo for this:  https://github.com/g-truc/glm/issues/235 .

**Comment by daw42** [comment]
This should be resolved in GLM 0.9.7.1.  Closing this issue.
