### ISSUE TITLE
i am having glm::two_pi not a a member error despite having downloaded glm

### ISSUE THREAD

**Issue by casio101** [daw42/glslcookbook#31]
ingredients/vbotorus.cpp:99:24: error: ‘two_pi’ is not a member of ‘glm’
    tex[tidx + 1] = v / glm::two_pi<float>();

**Comment by casio101** [comment]
to add the version of glm i have is 0.9.6.3

**Comment by casio101** [comment]
cmake couldnt find it, resolved it by putting glm in the folder its look at

**Comment by hays0503** [comment]
The problem when you compile as correct ??!

make -f Makefile
[  1%] Building CXX object ingredients/CMakeFiles/ingredients.dir/vbotorus.cpp.o
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp: In member function ‘void VBOTorus::generateVerts(float*, float*, float*, unsigned int*, float, float)’:
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:80:21: error: ‘two_pi’ is not a member of ‘glm’
  float ringFactor = glm::two_pi<float>() / rings;
                     ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:80:33: error: expected primary-expression before ‘float’
  float ringFactor = glm::two_pi<float>() / rings;
                                 ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:81:21: error: ‘two_pi’ is not a member of ‘glm’
  float sideFactor = glm::two_pi<float>() / sides;
                     ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:81:33: error: expected primary-expression before ‘float’
  float sideFactor = glm::two_pi<float>() / sides;
                                 ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:98:20: error: ‘two_pi’ is not a member of ‘glm’
    tex[tidx] = u / glm::two_pi<float>();
                    ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:98:32: error: expected primary-expression before ‘float’
    tex[tidx] = u / glm::two_pi<float>();
                                ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:99:24: error: ‘two_pi’ is not a member of ‘glm’
    tex[tidx + 1] = v / glm::two_pi<float>();
                        ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:99:36: error: expected primary-expression before ‘float’
    tex[tidx + 1] = v / glm::two_pi<float>();
                                    ^
