### ISSUE TITLE
i am having errors in the make phase something about libX11.so.6, i think i got the package on my system

### ISSUE THREAD

**Issue by casio101** [daw42/glslcookbook#32]
Linking CXX executable chapter01
/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [chapter01/chapter01] Error 1
make[1]: *** [chapter01/CMakeFiles/chapter01.dir/all] Error 2
make: *** [all] Error 2

**Comment by pttsukida** [comment]
I have the same problem..

**Comment by daw42** [comment]
Try installing the x11 developer packages for your Linux distro.

**Comment by zryan3** [comment]
I wanted to note that I've run into the same problem on Linux Mint 17.2. I made sure to download every libx11 package I could find from doing a `apt-cache search libx11` . @casio101 and @wppr have you guys had any success resolving this? Interestingly, I had no issues building on Ubuntu 14.04. I was also able to build https://github.com/openglsuperbible/sb7code which also depends on GLFW3 and uses X11 on Linux, so I'm trying to see where the difference in building lies between that project and this one.

**Comment by daw42** [comment]
Thanks @zryan3, want to make a pull request with this fix?

**Comment by zryan3** [comment]
Sure, I can get one up in a jiffy

**Comment by daw42** [comment]
Fixed with PR #39
