### ISSUE TITLE
The problem when you compile as correct ??!

### ISSUE THREAD

**Issue by hays0503** [daw42/glslcookbook#33]
The problem when you compile as correct ??!

make -f Makefile
[  1%] Building CXX object ingredients/CMakeFiles/ingredients.dir/vbotorus.cpp.o
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp: In member function ‘void VBOTorus::generateVerts(float*, float*, float*, unsigned int*, float, float)’:
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:80:21: error: ‘two_pi’ is not a member of ‘glm’
  float ringFactor = glm::two_pi<float>() / rings;
                     ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:80:33: error: expected primary-expression before ‘float’
  float ringFactor = glm::two_pi<float>() / rings;
                                 ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:81:21: error: ‘two_pi’ is not a member of ‘glm’
  float sideFactor = glm::two_pi<float>() / sides;
                     ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:81:33: error: expected primary-expression before ‘float’
  float sideFactor = glm::two_pi<float>() / sides;
                                 ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:98:20: error: ‘two_pi’ is not a member of ‘glm’
    tex[tidx] = u / glm::two_pi<float>();
                    ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:98:32: error: expected primary-expression before ‘float’
    tex[tidx] = u / glm::two_pi<float>();
                                ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:99:24: error: ‘two_pi’ is not a member of ‘glm’
    tex[tidx + 1] = v / glm::two_pi<float>();
                        ^
/home/hays/program/glslcookbook-master/ingredients/vbotorus.cpp:99:36: error: expected primary-expression before ‘float’
    tex[tidx + 1] = v / glm::two_pi<float>();

**Comment by daw42** [comment]
Please check that you have the latest version of the code.  The `glm::two_pi()` statements should have the `float` parameter.  

`glm::two_pi<float>()`

**Comment by hays0503** [comment]
sudo apt-get install libglm-dev
because GLM has established a library
source code downloaded from GitHub today

**Comment by daw42** [comment]
Your compiler error trace indicates that the `<float>` type parameter is missing.  In the latest version of the code, it is there:

https://github.com/daw42/glslcookbook/blob/master/ingredients/vbotorus.cpp#L98
