### ISSUE TITLE
failed to build on windows and on linux

### ISSUE THREAD

**Issue by gocoffeecup** [daw42/glslcookbook#34]
On Windows in visual studio express 2012 i get the error message:

Error	1	error LNK1107: invalid or corrupt file: cannot read at 0x1C196

and on Linux:

[ 22%] Linking CXX executable chapter01
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `initExtensions':
x11_init.c:(.text+0x1ac5): undefined reference to `XineramaQueryExtension'
x11_init.c:(.text+0x1adf): undefined reference to `XineramaIsActive'
/usr/local/lib/libglfw3.a(x11_init.c.o): In function `_glfwCreateCursor':
x11_init.c:(.text+0x218d): undefined reference to `XcursorImageCreate'
x11_init.c:(.text+0x2264): undefined reference to `XcursorImageLoadCursor'
x11_init.c:(.text+0x2274): undefined reference to `XcursorImageDestroy'

I'm using the latest verisions of cmake and glfw.

**Comment by daw42** [comment]
I haven't seen the Windows error before, and your error message doesn't indicate which file.  Perhaps you had some file corruption in the process of a download.

On Linux, you probably need one of the x11 developer packages installed.  Sorry, I'm not sure which one(s).
