### ISSUE TITLE
CMake unable to find GLFW3_LIBRARY

### ISSUE THREAD

**Issue by SyedRagib** [daw42/glslcookbook#36]
Hello I am stuck on step 10) of "Compiling for Windows with Visual Studio 2012". Specifically when I press configure on CMake, it can find the GLFW3_INCLUDE_DIR but cannot find GLFW3_LIBRARY. If it helps, cmake can find GLM_INCLUDE_DIR. I have placed all the files in "ProgramFiles(x86)" as stated in the instructions.

**Comment by zryan3** [comment]
Are you pointing the GLFW3_LIBRARY path to the path of the shared object or DLL files on CMake?

**Comment by daw42** [comment]
Just updated the CMAKE files.  Please give it another try.  Use `CMAKE_PREFIX_PATH` to point to the location of your depencencies.

**Comment by daw42** [comment]
No response from original reporter.  Closing.
