### ISSUE TITLE
License

### ISSUE THREAD

**Issue by godbyk** [daw42/glslcookbook#37]
What license is this code available under? (I grepped the files here and the book itself but couldn't find any mention of a license.)

**Comment by daw42** [comment]
Good question.  It probably should have a license, but doesn't have one yet.  I'll think about this and update the repo with appropriate licensing text at some point.  More than likely, I'll use a Creative Commons, MIT, or similar.

**Comment by kphillisjr** [comment]
I am also curious to find out what the license for this git repository (as well as the Book Sample Code). I believe that using a license that is approved by the [Open Source Initiative (OSI)](https://opensource.org/) and listed on the [Software Package Data Exchange (aka SPDX)](https://spdx.org/) is a good idea. I probably should mention that currently there is no Creative Commons licenses listed under the OSI, but does has an SPDX entry ([SPDX CC0-1.0](https://spdx.org/licenses/CC0-1.0.html)).

Anyways I have made a short list of licenses similar to the MIT License along with a link to both the OSI Description, SPDX Identifier, and a short informative document over the license ad TLDRLegal.

License Name | OSI Identifier | SPDX Identifier |  TLDRLegal Info
------------ | ------------- | -------------  | -------------
Free Public License 1.0.0 ( also called Zero Clause BSD) |  [FPL-1.0.0](https://opensource.org/licenses/FPL-1.0.0)  | [0BSD](https://spdx.org/licenses/0BSD.html ) | [0BSD](https://tldrlegal.com/license/bsd-0-clause-license) or [FPL-1.0.0](https://tldrlegal.com/license/free-public-license-1.0.0)
The Unlicense | (not recommended) [1] | [Unlicense](https://spdx.org/licenses/Unlicense.html) | [Unlicense](https://tldrlegal.com/license/unlicense)
BSD 1-clause [2] | not listed  | not listed  | not listed.
Boost Software License 1.0 | [BSL-1.0](https://opensource.org/licenses/BSL-1.0) | [BSL-1.0](https://spdx.org/licenses/BSL-1.0.html) | [BSL-1.0](https://tldrlegal.com/license/boost-software-license-1.0-explained)
MIT License | [MIT](https://opensource.org/licenses/MIT) | [MIT](https://spdx.org/licenses/MIT.html) | [MIT/Expat](https://tldrlegal.com/license/mit-license)
ZLib License | [Zlib](https://opensource.org/licenses/Zlib) | [Zlib](https://opensource.org/licenses/Zlib) | [Zlib](https://tldrlegal.com/license/zlib-libpng-license-(zlib))
Apache 2.0 License | [Apache-2.0](https://opensource.org/licenses/Apache-2.0) | [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html) | [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

[1] OSI does not support public domain dedications. This information is on the [[Open Source Initiative - Frequently Answered Questions]( https://opensource.org/faq#public-domain)].

[2] This license is similar to the Boost Software License 1.0. The KDE Project source tree contains a copy of this in the following location (https://websvn.kde.org/trunk/playground/sysadmin/secpolicy/ ). This is simply the 2-Clause BSD License with the following license removed...
> 2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

**Comment by daw42** [comment]
Thanks @kphillisjr, that is really helpful.

**Comment by daw42** [comment]
The publisher has not responded to my emails about this, and I haven't found any other examples of licenses used by Packt authors.  Still looking.

**Comment by kphillisjr** [comment]
A great way to see examples of the licenses is to check out the repositories on [Packt Publishing's Github Account](https://github.com/PacktPublishing/).

**Comment by daw42** [comment]
Thanks again!  I wasn't aware of this.  Looks like most use MIT.

**Comment by daw42** [comment]
Added MIT license.
