### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file '..\ingredients\Debug\ingredients.lib'

### ISSUE THREAD

**Issue by chengtseng** [daw42/glslcookbook#43]
Not sure if the git still being maintained. When I open GLSLCOOKBOOK.sln, and right click on ALL_BUILD and build, I keep receiving
LINK : fatal error LNK1104: cannot open file '..\ingredients\Debug\ingredients.lib'
and I didn't have this 'ingredients.lib' in the specified location. Any idea?
I am using visual studio 2015 with CMake 3.50

**Comment by chengtseng** [comment]
To be more specific:
When I do the step 7, I set the FindGLM.cmake to the following.

SET(_glm_HEADER_SEARCH_DIRS
    "/usr/include"
    "/usr/local/include"
	"C:/dev/OpenGL/glm"------------------------------>this is the root folder of my glm
    "C:/Program Files (x86)/glm" )

So it should be OK. But it seems that it is still glm issue,,

**Comment by daw42** [comment]
`ingredients.lib` is compiled from the source in the `ingredients` directory.  It's part of the project itself, not a separate library.  

I don't have Visual Studio available to reproduce this issue, but when I have a chance, I'll take a look.  In the meantime, if you resolve the issue, a PR is welcome.

Thanks.

**Comment by shun2522** [comment]
@chengtseng 
I've got same problem, but solved by fixing `vbomeshadj.cpp`.

Try modifying `uint` to `unsigned int` at 377 of vbomeshadj.cpp, and it'll be compiled.

**Comment by daw42** [comment]
Just updated the CMAKE build system.  Give it another try.
