### ISSUE TITLE
shader files can't be opened

### ISSUE THREAD

**Issue by robert-g-liu** [daw42/glslcookbook#50]
When I saw that most examples can run MasOs from this github page I was so interested in trying that immediately on my MasOs Sierria with Xcode 9.2. 

With the latest glfw snapshot I did build all the examples successfully. When I tried the chapter 6 point sprite example, I got the runtime error message saying that the pointsprite.vs can't be opened.

Here is the code line: prog.compileShader("shader/pointsprite.vs");

I found the root cause issue is in Xcode debug, the current working directory is <...>/chapter06/Debug. However, in fact "shader" directory is at the same level as "Debug" directory. Further, "media" directory is at the same level as "chapter06" directory. 

So if we follow the instructions in the github only we are not able to run any examples. 

Please suggest any solution on this. Is there any Xcode setting for changing the working directory?

**Comment by daw42** [comment]
You could copy the shader directory into the `Debug` directory as a temporary fix.  Alternatively, you might be able to specify an alternate working directory in the Xcode settings somewhere.

A PR is welcome if you have a fix for the cmake files.

Thanks.

**Comment by Alabuta** [comment]
std::filesystem/boost::filesystem might be helpful.
