### ISSUE TITLE
CMake Error in ingredients/CMakeLists.txt (Xubuntu 16.04, cmake 3.5.1, g++ 5.4.0)

### ISSUE THREAD

**Issue by jimofthecorn** [daw42/glslcookbook#51]
CMake Error in ingredients/CMakeLists.txt:
     Target "ingredients" requires the language dialect "CXX17" (with compiler
     extensions), but CMake does not know the compile flags to use to enable it.

**Comment by daw42** [comment]
Support for C++ 17 was added to CMake in version 3.8.  Can you upgrade your CMake?  If not, you probably can just switch to C++ 14 (or 11).  I don't think that I use very many (if any) C++ 17 specific features.
