### ISSUE TITLE
Error when compile chapter 2 or 3 in file aabb.h

### ISSUE THREAD

**Issue by MVOlekhno** [daw42/glslcookbook#52]
Hi! 
System

> glfw3.lib - compile ok  x64
> glm0.9.9.0 - just include folder
> ingredients.lib - compile ok x64  
  Visual Studio 15 2017 Win64 - cmake configure & generate  --- no problem
chapter 1 - compile ok
chapter 2 - compile error in aabb.h  24 error just in line 43 42

> Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0040	expected an identifier	chapter03	C:\GLSL\glslcookbook-master\ingredients\aabb.h	42	
Error (active)	E0040	expected an identifier	chapter03	C:\GLSL\glslcookbook-master\ingredients\aabb.h	43	
Error	C2589	'(': illegal token on right side of '::'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2144	syntax error: 'unknown-type' should be preceded by ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2144	syntax error: 'unknown-type' should be preceded by ';'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2143	syntax error: missing ')' before '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2530	'pt': references must be initialized	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2143	syntax error: missing ';' before '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2059	syntax error: '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2059	syntax error: ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2589	'(': illegal token on right side of '::'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Error	C2062	type 'unknown-type' unexpected	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Error	C2059	syntax error: ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Error	C2589	'(': illegal token on right side of '::'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2144	syntax error: 'unknown-type' should be preceded by ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2144	syntax error: 'unknown-type' should be preceded by ';'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2143	syntax error: missing ')' before '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2530	'pt': references must be initialized	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2143	syntax error: missing ';' before '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2059	syntax error: '>'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2059	syntax error: ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Error	C2589	'(': illegal token on right side of '::'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Error	C2062	type 'unknown-type' unexpected	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Error	C2059	syntax error: ')'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Warning	C4003	not enough arguments for function-like macro invocation 'max'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Warning	C4003	not enough arguments for function-like macro invocation 'max'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	
Warning	C4003	not enough arguments for function-like macro invocation 'max'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	42	
Warning	C4003	not enough arguments for function-like macro invocation 'max'	chapter03	c:\glsl\glslcookbook-master\ingredients\aabb.h	43	

> definition <max min> in minwindef.h 

>  #ifndef max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
#endif

#ifndef min
#define min(a,b)            (((a) < (b)) ? (a) : (b))
#endif  

How to solve this problem?

**Comment by daw42** [comment]
The Windows min/max macros should be disabled by this (in CMakeLists.txt):

```
if(MSVC)
  add_definitions(/DNOMINMAX)
endif()
```

Verify this is in your CMakeLists.txt?
