### ISSUE TITLE
chapter09 (smoke) uses point sprites, but most hardware has very low limits on point sizes

### ISSUE THREAD

**Issue by sreich** [daw42/glslcookbook#7]
I know this basically says "redo all of chapter 9", but this is a pretty real issue actually. 

Apparently this method uses point sprites.

There are two big issues with using point sprites, as I took a week of debugging to finally find out :(

Apparently, (a) a lot of hardware has a point size limit of 64.0. This tutorial goes up to 200, and setting it to 64 is just really small.

The other big issue is that when the center of a point sprite goes off-screen, the whole thing is clipped.

It'd be really cool if you could make another version of this same approach using something like geometry shaders or whatever. I really want to have a "particles like smoke, fully on the gpu"

**Comment by daw42** [comment]
Unfortunately, due to various reasons including tight, publisher imposed deadlines, this didn't make it into the 2nd edition.  I'd still like to do some examples that use the geometry shader or some other non-GL_POINT-based technique.  I may add them as a separate set of examples.

**Comment by daw42** [comment]
This has finally been addressed in the 3rd edition, now available:  https://github.com/PacktPublishing/OpenGL-4-Shading-Language-Cookbook-Third-Edition
