### ISSUE TITLE
Error when running some examples

### ISSUE THREAD

**Issue by TonderaiZR** [daw42/glslcookbook#8]
Hello

Hello does any one what this means.

genType glm::inversesqrt(const genType&) [with genType = float]: Assertion `x > genType(0)' failed.
Aborted (core dumped)

**Comment by picosk** [comment]
Thanks dangets/daw42! this works for me!
I had this before:
```
mesh->normals[v] = glm::normalize(mesh->normals[v]);
```
I fix it with:
```
	if(glm::length(mesh->normals[v])!=0.0f){
		mesh->normals[v] = glm::normalize(mesh->normals[v]);
	}else{
		mesh->normals[v] = glm::vec3(0.0, 0.0, 0.0);
	}
```
